Repository skoudoro/mailerlite-api-python, pull requests merged in 2020-04, with the labels that each got.

#4 Quick PR to update failing test
  .flake8
  .travis.yml
  mailerlite/__init__.py
  mailerlite/api.py
  mailerlite/campaign.py
  mailerlite/constants.py
  mailerlite/segment.py
  mailerlite/tests/test_campaign.py
  mailerlite/tests/test_client.py
  mailerlite/tests/test_group.py
  mailerlite/tests/test_subscriber.py
Labels: documentation

#5 add python 3.9 and OSX to Travis
  .codecov.yml
  .travis.yml
Labels: maintenance

#6 Add Check headers
  mailerlite/account.py
  mailerlite/api.py
  mailerlite/campaign.py
  mailerlite/client.py
  mailerlite/field.py
  mailerlite/group.py
  mailerlite/segment.py
  mailerlite/subscriber.py
  mailerlite/tests/test_client.py
Labels: enhancement

#3 add subscribers count
  README.md
  mailerlite/subscriber.py
Labels: enhancement

#9 [FIX] disable email update for a subscriber
  README.md
  mailerlite/subscriber.py
  mailerlite/tests/test_group.py
  mailerlite/tests/test_subscriber.py
Labels: bug
